In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
df = pd.read_csv('ppdata\\Netflix-R\\netflix_titles.csv')

In [3]:
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,TV Show,3%,NaN,"João Miguel, Bianca Comparato, Michel Gomes, R...",Brazil,"August 14, 2020",2020,TV-MA,4 Seasons,"International TV Shows, TV Dramas, TV Sci-Fi &...",In a future where the elite inhabit an island ...
1,s2,Movie,7:19,Jorge Michel Grau,"Demián Bichir, Héctor Bonilla, Oscar Serrano, ...",Mexico,"December 23, 2016",2016,TV-MA,93 min,"Dramas, International Movies",After a devastating earthquake hits Mexico Cit...
2,s3,Movie,23:59,Gilbert Chan,"Tedd Chan, Stella Chung, Henley Hii, Lawrence ...",Singapore,"December 20, 2018",2011,R,78 min,"Horror Movies, International Movies","When an army recruit is found dead, his fellow..."
3,s4,Movie,9,Shane Acker,"Elijah Wood, John C. Reilly, Jennifer Connelly...",United States,"November 16, 2017",2009,PG-13,80 min,"Action & Adventure, Independent Movies, Sci-Fi...","In a postapocalyptic world, rag-doll robots hi..."
4,s5,Movie,21,Robert Luketic,"Jim Sturgess, Kevin Spacey, Kate Bosworth, Aar...",United States,"January 1, 2020",2008,PG-13,123 min,Dramas,A brilliant group of students become card-coun...

In [4]:
df.isnull().sum()

show_id            0
type               0
title              0
director        2389
cast             718
country          507
date_added        10
release_year       0
rating             7
duration           0
listed_in          0
description        0
dtype: int64

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7787 entries, 0 to 7786
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       7787 non-null   object
 1   type          7787 non-null   object
 2   title         7787 non-null   object
 3   director      5398 non-null   object
 4   cast          7069 non-null   object
 5   country       7280 non-null   object
 6   date_added    7777 non-null   object
 7   release_year  7787 non-null   int64
 8   rating        7780 non-null   object
 9   duration      7787 non-null   object
 10  listed_in     7787 non-null   object
 11  description   7787 non-null   object
dtypes: int64(1), object(11)
memory usage: 730.2+ KB

In [6]:
df.columns

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in', 'description'],
      dtype='object')

Handling missing value

In [7]:
df['director'] = df['director'].fillna('Missing')

In [8]:
df[df['rating'].isna()]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
67,s68,Movie,13TH: A Conversation with Oprah Winfrey & Ava ...,Missing,"Oprah Winfrey, Ava DuVernay",NaN,"January 26, 2017",2017,NaN,37 min,Movies,Oprah Winfrey sits down with director Ava DuVe...
2359,s2360,TV Show,Gargantia on the Verdurous Planet,Missing,"Kaito Ishikawa, Hisako Kanemoto, Ai Kayano, Ka...",Japan,"December 1, 2016",2013,NaN,1 Season,"Anime Series, International TV Shows","After falling through a wormhole, a space-dwel..."
3660,s3661,TV Show,Little Lunch,Missing,"Flynn Curry, Olivia Deeble, Madison Lu, Oisín ...",Australia,"February 1, 2018",2015,NaN,1 Season,"Kids' TV, TV Comedies","Adopting a child's perspective, this show take..."
3736,s3737,Movie,Louis C.K. 2017,Louis C.K.,Louis C.K.,United States,"April 4, 2017",2017,NaN,74 min,Movies,"Louis C.K. muses on religion, eternal love, gi..."
3737,s3738,Movie,Louis C.K.: Hilarious,Louis C.K.,Louis C.K.,United States,"September 16, 2016",2010,NaN,84 min,Movies,Emmy-winning comedy writer Louis C.K. brings h...
3738,s3739,Movie,Louis C.K.: Live at the Comedy Store,Louis C.K.,Louis C.K.,United States,"August 15, 2016",2015,NaN,66 min,Movies,The comic puts his trademark hilarious/thought...
4323,s4324,Movie,My Honor Was Loyalty,Alessandro Pepe,"Leone Frisa, Paolo Vaccarino, Francesco Miglio...",Italy,"March 1, 2017",2015,NaN,115 min,Dramas,"Amid the chaos and horror of World War II, a c..."

In [9]:
df['rating'].value_counts()

TV-MA       2863
TV-14       1931
TV-PG        806
R            665
PG-13        386
TV-Y         280
TV-Y7        271
PG           247
TV-G         194
NR            84
G             39
TV-Y7-FV       6
UR             5
NC-17          3
Name: rating, dtype: int64

In [10]:
replace_nan = {67: 'TV-PG',
               2359 :'PG-13',
               3660 : 'PG',
               3736 : 'PG-13',
               3737: 'PG-13',
               3738: 'G',
              4323: 'PG-13'}

In [11]:
for id, rate in replace_nan.items():
    df.iloc[id, 8] = rate

In [12]:
df.iloc[67,:]

show_id                                                       s68
type                                                        Movie
title           13TH: A Conversation with Oprah Winfrey & Ava ...
director                                                  Missing
cast                                  Oprah Winfrey, Ava DuVernay
country                                                       NaN
date_added                                       January 26, 2017
release_year                                                 2017
rating                                                      TV-PG
duration                                                   37 min
listed_in                                                  Movies
description     Oprah Winfrey sits down with director Ava DuVe...
Name: 67, dtype: object

In [13]:
df['country'].value_counts()

United States                                         2555
India                                                  923
United Kingdom                                         397
Japan                                                  226
South Korea                                            183
                                                      ...
Spain, Mexico, France                                    1
United Kingdom, United States, France, Germany           1
United Kingdom, Italy, Israel, Peru, United States       1
India, Pakistan                                          1
Indonesia, Netherlands                                   1
Name: country, Length: 681, dtype: int64

Handling the missing value of country

In [14]:
def country_nan(df, variable):
    frequent = df['country'].mode()[0]
    df[variable].fillna(frequent,inplace = True)

In [15]:
country_nan(df,'country')

In [16]:
df['country'].isnull().sum()

0

In [17]:
df['cast'].fillna('Missing', inplace = True)

In [18]:
df['cast'].isnull().sum()

0

In [19]:
df[df['date_added'].isna()]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
258,s259,TV Show,A Young Doctor's Notebook and Other Stories,Missing,"Daniel Radcliffe, Jon Hamm, Adam Godley, Chris...",United Kingdom,NaN,2013,TV-MA,2 Seasons,"British TV Shows, TV Comedies, TV Dramas","Set during the Russian Revolution, this comic ..."
549,s550,TV Show,Anthony Bourdain: Parts Unknown,Missing,Anthony Bourdain,United States,NaN,2018,TV-PG,5 Seasons,Docuseries,This CNN original series has chef Anthony Bour...
2263,s2264,TV Show,Frasier,Missing,"Kelsey Grammer, Jane Leeves, David Hyde Pierce...",United States,NaN,2003,TV-PG,11 Seasons,"Classic & Cult TV, TV Comedies",Frasier Crane is a snooty but lovable Seattle ...
2288,s2289,TV Show,Friends,Missing,"Jennifer Aniston, Courteney Cox, Lisa Kudrow, ...",United States,NaN,2003,TV-14,10 Seasons,"Classic & Cult TV, TV Comedies",This hit sitcom follows the merry misadventure...
2555,s2556,TV Show,Gunslinger Girl,Missing,"Yuuka Nanri, Kanako Mitsuhashi, Eri Sendai, Am...",Japan,NaN,2008,TV-14,2 Seasons,"Anime Series, Crime TV Shows","On the surface, the Social Welfare Agency appe..."
3374,s3375,TV Show,Kikoriki,Missing,Igor Dmitriev,United States,NaN,2010,TV-Y,2 Seasons,Kids' TV,A wacky rabbit and his gang of animal pals hav...
3492,s3493,TV Show,La Familia P. Luche,Missing,"Eugenio Derbez, Consuelo Duval, Luis Manuel Áv...",United States,NaN,2012,TV-14,3 Seasons,"International TV Shows, Spanish-Language TV Sh...","This irreverent sitcom featues Ludovico, Feder..."
3946,s3947,TV Show,Maron,Missing,"Marc Maron, Judd Hirsch, Josh Brener, Nora Zeh...",United States,NaN,2016,TV-MA,4 Seasons,TV Comedies,"Marc Maron stars as Marc Maron, who interviews..."
5137,s5138,TV Show,Red vs. Blue,Missing,"Burnie Burns, Jason Saldaña, Gustavo Sorola, G...",United States,NaN,2015,NR,13 Seasons,"TV Action & Adventure, TV Comedies, TV Sci-Fi ...","This parody of first-person shooter games, mil..."
6065,s6066,TV Show,The Adventures of Figaro Pho,Missing,"Luke Jurevicius, Craig Behenna, Charlotte Haml...",Australia,NaN,2015,TV-Y7,2 Seasons,"Kids' TV, TV Comedies","Imagine your worst fears, then multiply them: ..."

In [20]:
df['date_added'].fillna('Missing', inplace = True)

In [21]:
df.isnull().sum()

show_id         0
type            0
title           0
director        0
cast            0
country         0
date_added      0
release_year    0
rating          0
duration        0
listed_in       0
description     0
dtype: int64

In [29]:
df['cast'] = df['cast'].apply(lambda x : x.replace(',', ''))
df['director'] = df['director'].apply(lambda x : x.replace(',', ''))
df['listed_in'] = df['listed_in'].apply(lambda x : x.replace(',',''))
df['listed_in'] = df['listed_in'].apply(lambda x : x.replace('&',''))

In [30]:
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,TV Show,3%,Missing,João Miguel Bianca Comparato Michel Gomes Rodo...,Brazil,"August 14, 2020",2020,TV-MA,4 Seasons,International TV Shows TV Dramas TV Sci-Fi Fa...,In a future where the elite inhabit an island ...
1,s2,Movie,7:19,Jorge Michel Grau,Demián Bichir Héctor Bonilla Oscar Serrano Aza...,Mexico,"December 23, 2016",2016,TV-MA,93 min,Dramas International Movies,After a devastating earthquake hits Mexico Cit...
2,s3,Movie,23:59,Gilbert Chan,Tedd Chan Stella Chung Henley Hii Lawrence Koh...,Singapore,"December 20, 2018",2011,R,78 min,Horror Movies International Movies,"When an army recruit is found dead, his fellow..."
3,s4,Movie,9,Shane Acker,Elijah Wood John C. Reilly Jennifer Connelly C...,United States,"November 16, 2017",2009,PG-13,80 min,Action Adventure Independent Movies Sci-Fi F...,"In a postapocalyptic world, rag-doll robots hi..."
4,s5,Movie,21,Robert Luketic,Jim Sturgess Kevin Spacey Kate Bosworth Aaron ...,United States,"January 1, 2020",2008,PG-13,123 min,Dramas,A brilliant group of students become card-coun...

In [31]:
df['total'] = df['type'] + df['director'] + df['cast'] + df['country'] + df['rating'] + df['duration'] + df['listed_in'] + df['description']

In [32]:
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,total
0,s1,TV Show,3%,Missing,João Miguel Bianca Comparato Michel Gomes Rodo...,Brazil,"August 14, 2020",2020,TV-MA,4 Seasons,International TV Shows TV Dramas TV Sci-Fi Fa...,In a future where the elite inhabit an island ...,TV ShowMissingJoão Miguel Bianca Comparato Mic...
1,s2,Movie,7:19,Jorge Michel Grau,Demián Bichir Héctor Bonilla Oscar Serrano Aza...,Mexico,"December 23, 2016",2016,TV-MA,93 min,Dramas International Movies,After a devastating earthquake hits Mexico Cit...,MovieJorge Michel GrauDemián Bichir Héctor Bon...
2,s3,Movie,23:59,Gilbert Chan,Tedd Chan Stella Chung Henley Hii Lawrence Koh...,Singapore,"December 20, 2018",2011,R,78 min,Horror Movies International Movies,"When an army recruit is found dead, his fellow...",MovieGilbert ChanTedd Chan Stella Chung Henley...
3,s4,Movie,9,Shane Acker,Elijah Wood John C. Reilly Jennifer Connelly C...,United States,"November 16, 2017",2009,PG-13,80 min,Action Adventure Independent Movies Sci-Fi F...,"In a postapocalyptic world, rag-doll robots hi...",MovieShane AckerElijah Wood John C. Reilly Jen...
4,s5,Movie,21,Robert Luketic,Jim Sturgess Kevin Spacey Kate Bosworth Aaron ...,United States,"January 1, 2020",2008,PG-13,123 min,Dramas,A brilliant group of students become card-coun...,MovieRobert LuketicJim Sturgess Kevin Spacey K...

In [33]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity 
from nltk.tokenize import word_tokenize

In [34]:
tfv = CountVectorizer()
text_features = tfv.fit_transform(df['total'])

In [36]:
similarity_matrix = cosine_similarity (text_features)
similarity_matrix

array([[1.        , 0.10375717, 0.05129892, ..., 0.13572418, 0.22041551,
        0.16323216],
       [0.10375717, 1.        , 0.06741999, ..., 0.15289416, 0.        ,
        0.        ],
       [0.05129892, 0.06741999, 1.        , ..., 0.07559289, 0.0238705 ,
        0.02357023],
       ...,
       [0.13572418, 0.15289416, 0.07559289, ..., 1.        , 0.08119979,
        0.37416574],
       [0.22041551, 0.        , 0.0238705 , ..., 0.08119979, 1.        ,
        0.07595545],
       [0.16323216, 0.        , 0.02357023, ..., 0.37416574, 0.07595545,
        1.        ]])

In [37]:
import random
movie_title = random.sample(list(df['title']),1)
movie_title[0]

'Wild Alaska'

In [54]:
def recommended_movie(movie_title):
    movie_index = df[df.title == movie_title].index
    similarity_score = similarity_matrix[movie_index]
    movie_frame = pd.DataFrame(similarity_score[0],columns=['cosine_similarity'])
    movie_frame=movie_frame.reset_index()
    movie_frame = movie_frame.sort_values(by='cosine_similarity',ascending=False)
    top10 = 10 
    top10_index = list(movie_frame['index'])[:10]
    recommended_movies = {}
    for i in top10_index:
        temp = df['title'][i]
        score = movie_frame['cosine_similarity'][i]
        recommended_movies[temp]=score
    for i in recommended_movies.items():
        print(i[0])

In [56]:
import random
movie_title = random.sample(list(df['title']),1)
print('Movies like movie ' ,movie_title[0], 'are :')
recommended_movie(movie_title[0])

Movies like movie  The Witness Who Didn't See Anything are :
The Witness Who Didn't See Anything
Journey of an African Colony
ARASHI's Diary -Voyage-
Sayed the Servant
What Did I Mess
Chasing Cameron
The Stranded
Alien Worlds
Win the Wilderness
Africa